// <auto-generated />
namespace House_Rent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kldsf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kldsf));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041704265_kldsf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
